return batches as dicts
danbider/lightning-pose pull request #22
Opened 2021-11-09 21:52 UTC by themattinthehatt

Instead of returning batches as lists, return them as dicts so that access is cleaner
images = batch["images"]
instead of 
images = batch[0]

Data loaders now also return the image index

2021-11-10 20:03 UTC, danbider requested changes
minor typechecking suggestions. looks great with dicts.

2021-11-11 02:17 UTC, danbider commented on pose_est_nets/datasets/datasets.py
> +    def __getitem__(self, idx: int) -> dict:
Done

2021-11-11 02:17 UTC, danbider commented on pose_est_nets/datasets/datasets.py
> +    def __getitem__(self, idx: int) -> dict:
Done

2021-11-11 02:38 UTC, danbider commented on pose_est_nets/datasets/datasets.py
> +            batch = super().__getitem__(idx)
Done

2021-11-11 02:44 UTC, danbider commented on pose_est_nets/datasets/preprocessing.py
> +                batch = pca_data.__getitem__(idx)
Done, switched to example dict

2021-11-11 16:20 UTC, danbider commented on pose_est_nets/models/heatmap_tracker.py
> +    def training_step(self, data_batch: Dict, batch_idx: int) -> Dict:
done, better

2021-11-11 16:20 UTC, danbider commented on pose_est_nets/models/regression_tracker.py
>      def training_step(self, data_batch: dict, batch_idx: int) -> dict:
done

2021-11-11 16:21 UTC, danbider commented on tests/test_subpixmaxima.py
> +    batch = dataset.__getitem__(idx=0)
done

2021-11-11 16:21 UTC, danbider commented on tests/test_subpixmaxima.py
> +    batch = dataset.__getitem__(idx=0)
done

2021-11-11 16:22 UTC, danbider commented on pose_est_nets/utils/plotting_utils.py
> -        joint_labels = ["bp_%i" % n for n in range(model.num_keypoints)]
leaving it for now

2021-11-11 16:36 UTC, themattinthehatt commented on pose_est_nets/utils/plotting_utils.py
> -        joint_labels = ["bp_%i" % n for n in range(model.num_keypoints)]
no, dlc uses the name of the network, but we should leave to be consistent - maybe we can fill this out with more informative info later

2021-11-11 16:37 UTC, themattinthehatt reviewed
Very solid PR

2021-11-11 16:37 UTC, merged