Normalized heatmap losses
danbider/lightning-pose pull request #36
Opened 2022-05-16 13:34 UTC by themattinthehatt

* normalize ground truth heatmaps
* normalize heatmap output of model with softmax
* implement KL and JS heatmap losses with kornia
* filter out low-confidence bodyparts when computing unimodal loss

2022-05-16 19:22 UTC, danbider requested changes

2022-05-16 19:22 UTC, danbider commented on lightning_pose/losses/losses.py
>          epsilon: float = 0.0,
modify name?

2022-05-16 19:22 UTC, danbider commented on lightning_pose/models/heatmap_tracker.py
> +        self.temperature = torch.tensor(1000., device=self.device)  # soft argmax temp
needs to be tested -- varies as the number of pixels in a heatmap
add a comment saying to be careful here.

2022-05-16 19:22 UTC, danbider commented on lightning_pose/models/heatmap_tracker.py
> +        return spatial_softmax2d(heatmaps, temperature=torch.tensor([1.0]))
comment should be always 1.00 std softmax

2022-05-16 19:22 UTC, danbider commented on scripts/configs/losses/losses_params.yaml
> +  esilon: 0.0
typo

2022-05-16 19:22 UTC, danbider commented on scripts/configs/losses/losses_params.yaml
> +  esilon: 0.0
typo

2022-05-16 20:44 UTC, danbider approved these changes

2022-05-16 20:44 UTC, merged

2022-05-16 20:44 UTC, danbider commented
nice -- merging.

2022-06-16 14:45 UTC, Gam3356 commented on lightning_pose/losses/losses.py
>      @typechecked
Please check The IP