update subpixel maxima
danbider/lightning-pose pull request #72
Opened 2022-12-09 20:55 UTC by themattinthehatt

2022-12-10 00:52 UTC, danbider requested changes
only if you want...

2022-12-10 00:52 UTC, danbider commented on lightning_pose/models/heatmap_tracker.py
> +
if you have some energy left, you could, above the `HeatmapTracker`, copy and paste this into a `SubpixelMaxima` class. `self.upsample()` is one method, offsets can be made into `@property`.
the class could be initialized in `HeatmapTracker.__init__()` and its forward method can be called as `HeatmapTracker.subpixel_maxima(inputs)`.
Not urgent, but seems mostly copy and pasting and will lighten up the model script. up to you, looks good.

2022-12-16 14:36 UTC, themattinthehatt commented on scripts/predict_new_vids.py
> +            absolute_cfg_path, ".hydra/configs/config_toy-dataset.yaml"))
oops line 63 is a bug, will update this.

2022-12-16 14:53 UTC, danbider approved these changes

2022-12-16 14:53 UTC, merged